### ISSUE TITLE
Endpoint for getting details of an amenity

### ISSUE THREAD

**Issue by jmprathab** [jmprathab/MyHome#110]
## ⚠️ Is your feature request related to a problem? Please describe

* Get details of an amenity

## 💡 Describe the solution you'd like

* `GET /amenities/{amenityId}`

## Task Relationship

Subtask of: jmprathab/MyHome#93

**Comment by DDmit04** [comment]
What fields must be present in response? I see something like this:
```
  private String amenityId;
  private String description;
  private boolean isBooked;
  private LocalDateTime bookingStartDate;
  private LocalDateTime bookingEndDate;
```
May be without dates

**Comment by jmprathab** [comment]
> What fields must be present in response? I see something like this:
> 
> ```
>   private String amenityId;
>   private String description;
>   private boolean isBooked;
>   private LocalDateTime bookingStartDate;
>   private LocalDateTime bookingEndDate;
> ```
> 
> May be without dates

@DDmit04 Only `amenityId` and `description` should be part of the response.
