### ISSUE TITLE
Update an amenity booking

### ISSUE THREAD

**Issue by jmprathab** [jmprathab/MyHome#115]
## ⚠️ Is your feature request related to a problem? Please describe

* Update a future booking

## 💡 Describe the solution you'd like

* `PUT /amenities/{amenityId}/bookings/{bookingId}`
* Only allow updating a future booking
* Update postman collection

## Task Relationship

Subtask of: jmprathab/MyHome#94

**Comment by SouradipPoddar** [comment]
Hi,  I'm a beginner in open source. Can I give this a go?

**Comment by mslowiak** [comment]
Hey @SouradipPoddar. This issue is related with #93. Feel free to look for something different :-)

**Comment by mslowiak** [comment]
@jmprathab Same question just like in https://github.com/jmprathab/MyHome/issues/116

**Comment by jmprathab** [comment]
> @jmprathab Same question just like in #116

@mslowiak Users would like to modify the booking time slot.
Thinking about it, it feels like we should not implement this endpoint. 
Let users delete the booking and re-book if required. What do you think?

**Comment by mslowiak** [comment]
@jmprathab 
Yeah, I would focus on delete - create rather than modify in this special case.
We can think about it in the future.

**Comment by jmprathab** [comment]
Closing this as no fix intended. Will be taken up in future if the need arises.
