### ISSUE TITLE
Delete an amenity booking

### ISSUE THREAD

**Issue by jmprathab** [jmprathab/MyHome#116]
## ⚠️ Is your feature request related to a problem? Please describe

* Delete an amenity booking

## 💡 Describe the solution you'd like

* `DELETE /amenities/{amenityId}/bookings/{bookingId}`
* Only allow deleting a future booking
* Update postman collection

## Task Relationship

Subtask of: jmprathab/MyHome#94

**Comment by mslowiak** [comment]
I will work on that

**Comment by mslowiak** [comment]
Is this endpoint make sense? Could you describe a situation in which this will be valuable @jmprathab?

**Comment by jmprathab** [comment]
> Is this endpoint make sense? Could you describe a situation in which this will be valuable @jmprathab?

@mslowiak The idea is to cancel a future booking. Let's say I booked a Gym for a time slot, then I decided to cancel it.

**Comment by mslowiak** [comment]
> > Is this endpoint make sense? Could you describe a situation in which this will be valuable @jmprathab?
> 
> @mslowiak The idea is to cancel a future booking. Let's say I booked a Gym for a time slot, then I decided to cancel it.

@jmprathab Shouldn't the name of endpoint be a:
`/bookings/{bookingId}/amenities/{amenityId}`
instead of:
`/amenities/{amenityId}/bookings/{bookingId}` ?

**Comment by jmprathab** [comment]
> @jmprathab Shouldn't the name of endpoint be a:
> `/bookings/{bookingId}/amenities/{amenityId}`
> instead of:
> `/amenities/{amenityId}/bookings/{bookingId}` ?

@mslowiak Any specific problem with `/amenities/{amenityId}/bookings/{bookingId}`? I thought of keeping it consistent with rest of the HTTP methods on `/amenities/{amenityId}/bookings/{bookingId}`.

**Comment by mslowiak** [comment]
@jmprathab Amenity is a part of the booking, not like booking is a part of amenity this is why I asked that question.

**Comment by jmprathab** [comment]
> @jmprathab Amenity is a part of the booking, not like booking is a part of amenity this is why I asked that question.

Thinking in terms of that, would it not be applicable for all the tasks under jmprathab/MyHome#94? Do you think we should change all the endpoints in the parent story?

**Comment by mslowiak** [comment]
I think that it should be changed. If we don't want to make a noise in stories we can add another one which will fix all endpoints after final implementation

**Comment by jmprathab** [comment]
> I think that it should be changed. If we don't want to make a noise in stories we can add another one which will fix all endpoints after final implementation

Proposal sounds good 👍

**Comment by nlaert** [comment]
Hello, looking for my first PR on open source. Could I take this task or is anyone working on it already?

**Comment by jmprathab** [comment]
@nlaert This is dependent on github.com/jmprathab/MyHome#93 and unfortunately it is not completed yet. Feel free to pick some other issue.

**Comment by tomsajuk** [comment]
@jmprathab I see that the dependent is completed. Shall I take this up?

**Comment by mslowiak** [comment]
@tomsajuk Yes, you are right. Should I assign that to you? :)

**Comment by tomsajuk** [comment]
@mslowiak Yes please :)

**Comment by tomsajuk** [comment]
Wanted to know whether all the booking endpoints to be created in a separate class(AmenityBookingController) or want to include in the Amenity controller. Any suggestion?

**Comment by mslowiak** [comment]
It should be in amenity controller
Cc : @jmprathab
