### ISSUE TITLE
Adding CommunityAdmin to community doesn't actually add them

### ISSUE THREAD

**Issue by edwardUL99** [jmprathab/MyHome#121]
## 🐛 Describe the bug

When using Postman to add a user id to a community as an admin, in the response body, the added user id does not show up. I debugged the code and found it was not added in the community's admin set either. I am unclear of what Add community admin is supposed to do since, we can't seem to create a community admin, I assumed it was just add a user id

## ⚠️ Current behavior

When I add a user id to the request body for adding an admin to a specified community, the response body does not contain this user id so it was not successfully added

## ✅ Expected behavior

When a user id is added to the community as an admin, the user id should show up in the response body and also in the list of community admins request

## 💣 Steps to reproduce

- Run the create user endpoint and login, obtaining the bearer token to use for the following requests
- List all users and choose one to be admin and copy their user id
- List all communities and choose a community id to use in a add admin to community request
- Using this community id, in the add admin request body, paste the user id you obtained
- Submit the request and you'll see in the response body, the id does not appear. 
- Submit a list all admins for that community request and it does not appear also

I believe the issue is in this code:
 
    return communitySearch.map(community -> {
      adminsIds.forEach(adminId -> {
        communityAdminRepository.findByAdminId(adminId).map(admin -> {
          admin.getCommunities().add(community);
          community.getAdmins().add(communityAdminRepository.save(admin));
          return admin;
        });
      });
      return Optional.of(communityRepository.save(community));
    }).orElseGet(Optional::empty);

This is in the addAdminsToCommunity method of CommunitySDJPAService starting at line 98

In the forEach loop of adminIds (the set of admin ids being added), you are using the community admin repository to find an admin using this id. This admin is then saved in the community.getAdmins().add(communityAdminRepository.save(admin));  But this code is never reached since if this adminId is new and was not added to the community as an admin before it wouldn't have been saved, and hence findByAdminId would return an empty Optional object, and the map function never being called. Because of this, new admins are never added.

I can take a look at fixing this but need clarification on exactly who can be a community admin, i.e. is it just a user where their user id is added as the admin or is an admin separate to a user and needs to be created? Just thought I'd log the bug report and go from there.

## 📱 Tech info

- Device: Docker 
- OS: Ubuntu
- Library/App version: Java 8

**Comment by DDmit04** [comment]
May be we should megre `User` and `CommunityAdmin` entities?
And get something like this:
```
public class User extends BaseEntity {
  @NonNull
  private String name;
  @Column(unique = true, nullable = false)
  private String userId;
  @Column(unique = true, nullable = false)
  private String email;
  @Column(nullable = false)
  private String encryptedPassword;
  @ManyToMany(mappedBy = "admins")
  private Set<Community> communities = new HashSet<>();
}
```
And regular users will have an empty set of communities. Or add field `userRole` wich contain info about user's permissions

**Comment by edwardUL99** [comment]
> May be we should megre `User` and `CommunityAdmin` entities?
> And get something like this:
> 
> ```
> public class User extends BaseEntity {
>   @NonNull
>   private String name;
>   @Column(unique = true, nullable = false)
>   private String userId;
>   @Column(unique = true, nullable = false)
>   private String email;
>   @Column(nullable = false)
>   private String encryptedPassword;
>   @ManyToMany(mappedBy = "admins")
>   private Set<Community> communities = new HashSet<>();
> }
> ```
> 
> And regular users will have an empty set of communities. Or add field `userRole` wich contain info about user's permissions

I'm not sure. To be honest, I think it just requires changing the logic surrounding adding an admin. My understanding that adding a user to a community makes them an admin is wrong as they are different entities in the code and it's unclear how to map a user object to a community admin object. However, there does not appear to be an endpoint/means to create a community admin either is there, so where do we get the admin to add to the community in the first place? Since the only ids we have access to is list all users. List all admins of a community isn't helpful as those are already added to the community. Maybe @jmprathab knows more

**Comment by jmprathab** [comment]
> May be we should megre `User` and `CommunityAdmin` entities?
> And get something like this:
> 
> ```
> public class User extends BaseEntity {
>   @NonNull
>   private String name;
>   @Column(unique = true, nullable = false)
>   private String userId;
>   @Column(unique = true, nullable = false)
>   private String email;
>   @Column(nullable = false)
>   private String encryptedPassword;
>   @ManyToMany(mappedBy = "admins")
>   private Set<Community> communities = new HashSet<>();
> }
> ```
> 
> And regular users will have an empty set of communities. Or add field `userRole` wich contain info about user's permissions

The merged entity looks good.

To quote @edwardUL99 
> My understanding that adding a user to a community makes them an admin is wrong

This is true.

The idea is that all community admins should be a valid `User` entity(But, as of now, the implementation does not enforce that).

**Comment by edwardUL99** [comment]
> > May be we should megre `User` and `CommunityAdmin` entities?
> > And get something like this:
> > ```
> > public class User extends BaseEntity {
> >   @NonNull
> >   private String name;
> >   @Column(unique = true, nullable = false)
> >   private String userId;
> >   @Column(unique = true, nullable = false)
> >   private String email;
> >   @Column(nullable = false)
> >   private String encryptedPassword;
> >   @ManyToMany(mappedBy = "admins")
> >   private Set<Community> communities = new HashSet<>();
> > }
> > ```
> > 
> > 
> > And regular users will have an empty set of communities. Or add field `userRole` wich contain info about user's permissions
> 
> The merged entity looks good.
> 
> To quote @edwardUL99
> 
> > My understanding that adding a user to a community makes them an admin is wrong
> 
> This is true.
> 
> The idea is that all community admins should be a valid `User` entity(But, as of now, the implementation does not enforce that).

Merging them would require a large amount of testing and refactoring if I am correct? This may take me some amount of time so if time is an issue, you can let someone else take a look at it. But, this weekend I should have plenty of time to work away at it with little interruptions :)

**Comment by jmprathab** [comment]
> Merging them would require a large amount of testing and refactoring if I am correct? This may take me some amount of time so if time is an issue, you can let someone else take a look at it. But, this weekend I should have plenty of time to work away at it with little interruptions :)

You are right, it would require large amount of refactoring and testing. Feel free to do it at your convenience.

**Comment by edwardUL99** [comment]
> > Merging them would require a large amount of testing and refactoring if I am correct? This may take me some amount of time so if time is an issue, you can let someone else take a look at it. But, this weekend I should have plenty of time to work away at it with little interruptions :)
> 
> You are right, it would require large amount of refactoring and testing. Feel free to do it at your convenience.

SO I assume when this is finished there should no longer be a CommunityAdmin class?

**Comment by jmprathab** [comment]
> SO I assume when this is finished there should no longer be a CommunityAdmin class?

You are right.

**Comment by edwardUL99** [comment]
> > SO I assume when this is finished there should no longer be a CommunityAdmin class?
> 
> You are right.

Great I have an implementation done, just need to test it and see if there's anything else I need to do with it
