### ISSUE TITLE
@Data annotations on classes can still cause StackOwerflowException (@toString)

### ISSUE THREAD

**Issue by DDmit04** [jmprathab/MyHome#124]
### 🐛 Describe the bug

`@Data` incudes `@toString` and as `@EqualsAndHashCode` can case `StackOwerflowExcaption`

## ✅ Expected behavior

exlude some fiels from `@toString` like for `@EqualsAndHashCode`

## 📷 Screenshots

<img width="960" alt="123" src="https://user-images.githubusercontent.com/46588421/89847897-c8906780-db8d-11ea-8569-e9a4ad20ce6c.png">

<img width="960" alt="123" src="https://user-images.githubusercontent.com/46588421/89848619-4143f380-db8f-11ea-9e3e-58be39952a55.png">

**Comment by edwardUL99** [comment]
Would you mind listing the classes you found the issues in if you come across more? If I get the time I'll try and recreate it but would be helpful if you end up finding more to list them here.

**Comment by DDmit04** [comment]
@edwardUL99 all classes with bidirectional hibermate relationships

**Comment by edwardUL99** [comment]
I'll take a look sometime tomorrow

**Comment by edwardUL99** [comment]
Do you have steps to recreate?

**Comment by jmprathab** [comment]
> Do you have steps to recreate?

I just faced this issue now. @edwardUL99 To reproduce this, you can just try to call `toString` on a `Community` entity.
