### ISSUE TITLE
Adding house to community should only return newly added house id

### ISSUE THREAD

**Issue by jmprathab** [jmprathab/MyHome#127]
## 🐛 Describe the bug

* Adding house to community should only return newly added house id

## ⚠️ Current behavior

* It returns all the houses in the community

## ✅ Expected behavior

* Should return only newly added houses

## 💣 Steps to reproduce

* `POST` to `/communities/{communityId}/houses` endpoint

**Comment by SouradipPoddar** [comment]
Can I take this up?

**Comment by jmprathab** [comment]
@SouradipPoddar I am working on this. Feel free to pick up something else from the list. https://github.com/jmprathab/MyHome/issues

**Comment by edwardUL99** [comment]
This doesn't happen for me. All it does for me is return a list of the houses that were added in that request, no others

**Comment by jmprathab** [comment]
> This doesn't happen for me. All it does for me is return a list of the houses that were added in that request, no others

Strange. I do get a list of all houses. Are you not on the latest master?

**Comment by LeVoMihalcea** [comment]
Has this been fixed in the meantime? For me it works as expected. 
![image](https://user-images.githubusercontent.com/27742752/94986020-ecf03b00-0563-11eb-9adf-7f19380c4a6b.png)

**Comment by jmprathab** [comment]
@LeVoMihalcea I tried it, looks like it is fixed. Thanks for your time and verification!
