### ISSUE TITLE
400 on community house delete

### ISSUE THREAD

**Issue by Tobi406** [jmprathab/MyHome#131]
## 🐛 Describe the bug
A 400 is returned when deleting a house on a community

## ⚠️ Current behavior
A 400 is returned and the house is not removed

## ✅ Expected behavior
The house is removed

## 💣 Steps to reproduce
`curl -X DELETE -H "Authorization: Bearer {{AUTH_TOKEN}}" -I http://localhost:8080/communities/{{COMMUNITY_ID}}/houses/{{HOUSE_ID}}`

## 📱 Tech info

- Device: 
- OS: 
- Library/App version:

**Comment by edwardUL99** [comment]
I got 204 code with Postman but you're correct with the house not being removed. I have fixed the issue however if you want me to put a pull request out?

**Comment by jmprathab** [comment]
> I got 204 code with Postman but you're correct with the house not being removed. I have fixed the issue however if you want me to put a pull request out?

I think `204` is expected. If the removal bug is fixed, why not raise a PR?

**Comment by edwardUL99** [comment]
> > I got 204 code with Postman but you're correct with the house not being removed. I have fixed the issue however if you want me to put a pull request out?
> 
> I think `204` is expected. If the removal bug is fixed, why not raise a PR?

I came across an issue when removing a house that had house members added to it. Empty houses deleted fine but ones with members did not. I think I may have it fixed but will put out a pull request when I test it a bit more
