### ISSUE TITLE
Add current user as Admin when creating a community

### ISSUE THREAD

**Issue by jmprathab** [jmprathab/MyHome#149]
## 🐛 Describe the bug

* When creating a new community using `POST /communities` current user should be added as the Admin of the community

## ⚠️ Current behavior

* Admin list of newly created community is empty

## ✅ Expected behavior

* User who creates the community should be an admin of it - Verify this using `GET /communities/:communityId/admins`

## 💣 Steps to reproduce

* `POST /communities`

## 📱 Tech info

- Device: Not applicable
- OS: All
- Library/App version: latest master

**Comment by tomsajuk** [comment]
Hi @jmprathab Can I take this up?

**Comment by tomsajuk** [comment]
@jmprathab please review. I can take up the next one too related to this. 155
