### ISSUE TITLE
Allow only existing admins to add admins to a community

### ISSUE THREAD

**Issue by jmprathab** [jmprathab/MyHome#150]
## 🐛 Describe the bug

*`POST /communities/:communityId/admins` should be only restricted to existing admins of the community 
* Note: Can be only picked up after #149

## ⚠️ Current behavior

* Anyone can now call `POST /communities/:communityId/admins`

## ✅ Expected behavior

* Restrict `POST /communities/:communityId/admins` only to existing admins

## 💣 Steps to reproduce

* `POST /communities/:communityId/admins` on a newly created community

## 📱 Tech info

- Device: Not applicable
- OS: All
- Library/App version: latest master

**Comment by WOLFI3654** [comment]
Hey, @jmprathab I would like to tackle this issue :)

**Comment by jmprathab** [comment]
@WOLFI3654 Sure. Let me assign the issue to you.

**Comment by WOLFI3654** [comment]
Thank you very much!

**Comment by mslowiak** [comment]
@WOLFI3654 How it is going? :)

**Comment by WOLFI3654** [comment]
Please excuse the slight delay. I'll upload the code shortly :)
