### ISSUE TITLE
Implement Forgot Password functionality

### ISSUE THREAD

**Issue by jmprathab** [jmprathab/MyHome#151]
## ⚠️ Is your feature request related to a problem? Please describe

* Let users reset their password using an API

## 💡 Describe the solution you'd like

* Both "changing old password" and "resetting forgot password" should be supported 

## Implementation details

1. User hits `POST /user/password?action=forgot`
2. Server send a mail to User's mail Id with a token to reset password
3. User hits `POST /user/password?action=reset` and submits - Token, new password
4. Server resets the password to the new password

**Comment by jmprathab** [comment]
Following is the proposed approach which is yet to be finalized after brainstorming

1. User hits `POST /users/:userId/forgot`
2. Server send a mail to User's mail Id with a token to reset password
3. User hits `POST /users/:userId/reset` and submits - Token, new password
4. Server resets the password to the new password

**Comment by SrishtyC13** [comment]
I am taking this issue.

**Comment by jmprathab** [comment]
> I am taking this issue.

@SrishtyC13 Can you please describe the approach? The above-commented approach is not yet finalized.

I am going through https://www.baeldung.com/spring-security-registration-i-forgot-my-password as of now to see if there is a better approach.

**Comment by SrishtyC13** [comment]
Actually i am a noob in open source, so i am just searching for projects related to android, i got misunderstood in your issue, can you suggest me where to start for android.

**Comment by jmprathab** [comment]
@SrishtyC13 Not a problem :-) This project is not based on android.

**Comment by GuptaAkshay** [comment]
Hi, @jmprathab I would like to take this issue up.
Also, I went through the link you mentioned in the above comment, which seems doable.

**Comment by mslowiak** [comment]
Welcome on board @GuptaAkshay! Fell free to raise a PR :)

**Comment by GuptaAkshay** [comment]
@mslowiak I am going to follow the approach mentioned https://www.baeldung.com/spring-security-registration-i-forgot-my-password. Do we need to have a discussion on the approach or it is good to go?

**Comment by mslowiak** [comment]
@GuptaAkshay Everything is correct there but according to `PasswordResetToken` entity please create `SecurityTokens` instead which will contain `id`, `token`, `expiryDate`, `creationDate`,  `type`.

This will be needed in case of an account activation feature in the future.
So in your case, the `type` property should be `RESET`.

Any questions to that?

**Comment by GuptaAkshay** [comment]
@mslowiak I am sorry I will not able to continue on this task. please unassign the task.

**Comment by DDmit04** [comment]
can I work on this?

**Comment by mslowiak** [comment]
Go ahead @DDmit04  :)

**Comment by DDmit04** [comment]
News about this - now I writing tests

**Comment by mslowiak** [comment]
@DDmit04 thank you for an update. Did you implement this feature including that comment: https://github.com/jmprathab/MyHome/issues/151#issuecomment-705179829 ?

**Comment by DDmit04** [comment]
@mslowiak yes
