### ISSUE TITLE
Restrict creating new amenity to community admin

### ISSUE THREAD

**Issue by jmprathab** [jmprathab/MyHome#152]
## 🐛 Describe the bug

* Only community admin should be able to create a new amenity

## ⚠️ Current behavior

* Any logged in user can create an amenity 

## ✅ Expected behavior

* Only admins should be able to create a new amenity

## 💣 Steps to reproduce

* `POST /communities/{communityId}/amenities`

## 📱 Tech info

- Device: NA
- OS: All
- Library/App version: latest master

**Comment by fx0000** [comment]
Hello, I would like to start contribute into the project. Can you assign me to this issue?

**Comment by jmprathab** [comment]
@fx0000 Sure.
