### ISSUE TITLE
[FEATURE TASK] API access control

### ISSUE THREAD

**Issue by jmprathab** [jmprathab/MyHome#153]
## ⚠️ Is your feature request related to a problem? Please describe

* Story to track access control for all APIs

## Sub-tasks

- [x] Amenity creation(#152)
- [x] Adding community admin(#150)

**Comment by studentPavel** [comment]
Hi, could you tell me more about this issue? I'm just beginner.

**Comment by mslowiak** [comment]
@studentPavel Hi there. This task is a feature task - it means that it groups issues that are needed to finish business feature. It is just for tracking purpose

**Comment by fx0000** [comment]
Pull request [ **_#165_** ] related to the sub-task **_Amenity _creation__** [ _**#152**_ ]  was proposed recently. However, we should consider division of HTTP requests in a terms of security for particular REST controller. Thus, sets of security rules should exist for the every controller. There are many methods across all the controllers, which should be executed only by admin. The numbers of these privileged methods will be also increased in the future. With security controller division we can guarantees the better future developing related to the security.

**Comment by mslowiak** [comment]
@fx0000 What do you mean by `security controller division` ? Could you provide the real-life example?

**Comment by fx0000** [comment]
By security **_REST_** controller division I thought divide incoming requests by controllers in the security config. Currently implementation divide all request broadly into two sub-groups: public/authenticated. 

### Example
1. Incoming HTTP request match URL pattern related to specific REST controller like "/communities/** --> CommunityController" 
2. Community authorization filter will be added into the security filter chain to ensure authorization of the user.
3. Filter check if a requested URL is privileged (require admin rights) and user has rights to execute the request.

You can see the partial implementation of third step in  PR **_#165_** where the privileged action is authorized by new community filter.

**Comment by GabrielCsik** [comment]
Hello, could I work on this issue?
