### ISSUE TITLE
DataLoader class does nothing

### ISSUE THREAD

**Issue by DDmit04** [jmprathab/MyHome#158]
## ⚠️ Is your feature request related to a problem? Please describe

`DataLoader` and `TestDataConstants` classes do nothing (their functionality has been replaced with `data.sql`)

```
@Override public void run(String... args) {
    // loadPostmanData();
  }
```

## 💡 Describe the solution you'd like

Remove this clases

**Comment by jufab** [comment]
Could you assign it to me?

**Comment by mslowiak** [comment]
@jufab done :)
