### ISSUE TITLE
Endpoint to get all members of all houses a user is in

### ISSUE THREAD

**Issue by Tobi406** [jmprathab/MyHome#159]
## ⚠️ Is your feature request related to a problem? Please describe

The only current way I know of to get all members of all houses the user is in, is to get all houses of the member and then get all members of these houses. Which I suspect is a) ugly and b) not fast

This is required to do part of what is suggested in jmprathab/MyHome-Web#87

## 💡 Describe the solution you'd like

* A `GET` endpoint that can be used to get all members (or member ids) off all houses the user is in.
* Endpoint has to be - `GET /users/{userId}/housemates`
* Endpoint should support pagination with `limit` & `start` parameters (Reference Implementation: [PaymentService](https://github.com/jmprathab/MyHome/blob/master/service/src/main/java/com/myhome/services/PaymentService.java)::listAll)

**Comment by jmprathab** [comment]
* Endpoint has to be - `GET /users/{userId}/housemates`
* Endpoint should support pagination with `limit` & `start` parameters (Reference Implementation: [PaymentService](https://github.com/jmprathab/MyHome/blob/master/service/src/main/java/com/myhome/services/PaymentService.java)::listAll)

CC: @mslowiak

**Comment by mslowiak** [comment]
@jmprathab @Tobi406 I guess the endpoint name should be `/users/{userId}/houses` to not mislead end user (we have endpoint `/houses` and it is connected somehow)

**Comment by esalcidom** [comment]
Hi @Tobi406 I would like to help with this issue.

**Comment by jmprathab** [comment]
@esalcidom Sure. Feel free to raise a PR! Thanks for your interest and time!

**Comment by aishwarya-bommisetty** [comment]
@esalcidom, Can I work with you on this issue?

**Comment by mslowiak** [comment]
@aishwaryaaaaaaa 
Do you still want to work on that issue?
