### ISSUE TITLE
Replace HealthCheckController with Spring Actuator

### ISSUE THREAD

**Issue by mslowiak** [jmprathab/MyHome#160]
The actual controller should be deleted.
We should use Spring Actuator instead.

Reference:
https://www.baeldung.com/spring-boot-actuators

**Comment by jmprathab** [comment]
* Only Health endpoints can be enabled.

**Comment by ubaldop** [comment]
I can take this.

**Comment by mslowiak** [comment]
Great @P3trur0. Good luck!

**Comment by ubaldop** [comment]
#166 is on its way! 🚀

**Comment by mslowiak** [comment]
@P3trur0 please take a look on comments in your PR and create new, valid one :)

**Comment by ubaldop** [comment]
@mslowiak done!

**Comment by mslowiak** [comment]
@P3trur0 your commit message is 'added Spring Boot Actuator endpoints' but it should be 'Issue #160: Add Spring Boot Actuator endpoints'

**Comment by ubaldop** [comment]
@mslowiak done
