### ISSUE TITLE
Add a salt to the hashed password

### ISSUE THREAD

**Issue by BenTels** [jmprathab/MyHome#164]
## ⚠️ Is your feature request related to a problem? Please describe

As of the time of writing, the user password is stored in a hashed format (BCrypt). However, nothing but BCrypting is done to hash the password. This means that all users with the same password will have their passwords stored in the database with the same hash value. In case of an exposure of stored password hashes, this immediately exposes all passwords that are the same as soon as one of those passwords is known.

## 💡 Describe the solution you'd like

Simplest solution here is to add a salt to the password. For example, starting from current implementation:

```java
private void encryptUserPassword(UserDto request) {
    var salt = UUID.randomUUID().toString().substring(0, 6);
    request.setSalt(salt);
    request.setEncryptedPassword(passwordEncoder.encode(request.getPassword() + salt));
}
```

With, of course, some necessary refactorings to add the salt to User. It doesn't have to be exposed to the UI. 

## 🤚 Do you want to develop this feature yourself?

- [ ] Yes
- [x] No

**Comment by mslowiak** [comment]
BCrypt does not work in that way at least in `BCryptPasswordEncoder` implementation.

![image](https://user-images.githubusercontent.com/18486535/95498956-deab8000-09a4-11eb-8f56-4539994c30b3.png)

For 3 different users with the same password, the hashes are different.

There are salted, see encode docs:
https://docs.spring.io/spring-security/site/docs/3.2.5.RELEASE/apidocs/org/springframework/security/crypto/bcrypt/BCryptPasswordEncoder.html#encode(java.lang.CharSequence)

**Comment by BenTels** [comment]
Ugh, yes, BCrypt includes its own salt. Teach me to try thinking when I'm sick... Sorry.

Never mind. As long as there is no desire to use a different hashing algorithm, it will be okay. You'll have issues if you want to make that mechanism configurable though.
