### ISSUE TITLE
Add info about code style to CONTRIBUTING.md

### ISSUE THREAD

**Issue by mslowiak** [jmprathab/MyHome#168]
There should be information in CONTRIBUTING.md about the code style that we use.
This info is included only in README.md actually.

Code style:
https://github.com/square/java-code-styles

**Comment by HemantJoshi11** [comment]
@mslowiak I will update contribution.md file with code style information. You want me to update anything specific ?

**Comment by mslowiak** [comment]
@HemantJoshi11 We just want to have that information also in contributing guide, not a big deal :)
