### ISSUE TITLE
Migration of PaymentController to OpenApi yaml schema

### ISSUE THREAD

**Issue by mslowiak** [jmprathab/MyHome#172]
This task is a subtask for #169.

The steps that need to be done:
- convert all endpoints from controller to yaml file
- check that endpoints are working, in the same way, like before the change
- check the tests

An example can be found in PR #171.

**Comment by edwin9870** [comment]
Hello,

May I take this issue?

Regards!

**Comment by mslowiak** [comment]
@edwin9870 sure, go ahead
