### ISSUE TITLE
Migration of HouseMemberDocumentController to OpenApi yaml schema

### ISSUE THREAD

**Issue by mslowiak** [jmprathab/MyHome#173]
This task is a subtask for #169.

The steps that need to be done:
- convert all endpoints from controller to yaml file
- check that endpoints are working, in the same way, like before the change
- check the tests

An example can be found in PR #171.

**Comment by huyle101** [comment]
Hey @mslowiak 
May I take this task?
Thanks,

**Comment by mslowiak** [comment]
@huyle1097 sure, assigned :)
