### ISSUE TITLE
Migration of HouseController to OpenApi yaml schema

### ISSUE THREAD

**Issue by mslowiak** [jmprathab/MyHome#174]
This task is a subtask for #169.

The steps that need to be done:
- convert all endpoints from controller to yaml file
- check that endpoints are working, in the same way, like before the change
- check the tests

An example can be found in PR #171.

**Comment by hemantsonu20** [comment]
I would like to pick this.

**Comment by mslowiak** [comment]
Great @hemantsonu20. If you would have some questions feel free to catch me on our discord server :)

**Comment by edwin9870** [comment]
Hello,

May I take this issue?

**Comment by jmprathab** [comment]
@edwin9870 Sure.
