### ISSUE TITLE
Migration of CommunityController to OpenApi yaml schema

### ISSUE THREAD

**Issue by mslowiak** [jmprathab/MyHome#175]
This task is a subtask for #169.

The steps that need to be done:
- convert all endpoints from controller to yaml file
- check that endpoints are working, in the same way, like before the change
- check the tests

An example can be found in PR #171.

**Comment by SergeyHydra** [comment]
@mslowiak I'd like to take this on. Can you assign this issue to me? Thanks.

**Comment by mslowiak** [comment]
@SergeyHydra when you finish the amenity story then I can assign that to you :)

**Comment by huyle101** [comment]
@mslowiak May I take this task? ;)

**Comment by mslowiak** [comment]
@huyle1097 go ahead bro :)
