### ISSUE TITLE
Migration of AmenityController to OpenApi yaml schema

### ISSUE THREAD

**Issue by mslowiak** [jmprathab/MyHome#176]
This task is a subtask for #169.

The steps that need to be done:
- convert all endpoints from controller to yaml file
- check that endpoints are working, in the same way, like before the change
- check the tests

An example can be found in PR #171.

**Comment by SergeyHydra** [comment]
@mslowiak I'd like to take this on. Can you assign this issue to me? Thanks.

**Comment by SergeyHydra** [comment]
@mslowiak I need some help with Gradle, I'm new to it.

**Comment by mslowiak** [comment]
@SergeyHydra reach me via Discord :)

**Comment by SergeyHydra** [comment]
What is your nickname there?

**Comment by mslowiak** [comment]
> What is your nickname there?

slowiakovsky

**Comment by SergeyHydra** [comment]
> > What is your nickname there?
> 
> slowiakovsky

Not found. Can you join to conversation by link? 
https://discord.gg/VAMMnW
