### ISSUE TITLE
Setup integration-tests module

### ISSUE THREAD

**Issue by mslowiak** [jmprathab/MyHome#183]
Things to do:
- create an example integration test (can be for one endpoint, one case)
- configure `integration-tests` module to be able to run integration tests there

**Comment by everythings13** [comment]
Hi @mslowiak, would love to take it up. Lmk if it's still available.

**Comment by mslowiak** [comment]
@everythings13
Yes, it is available. Have you some experience with Gradle already? :)

**Comment by everythings13** [comment]
@mslowiak, not with Gradle. Have been working, however, with Maven for quite some time now!

**Comment by mslowiak** [comment]
@everythings13 
Okay, then the task is yours. If you got some troubles please join us on Discord and share your feelings :)
