### ISSUE TITLE
[FEATURE TASK] Email templates

### ISSUE THREAD

**Issue by mslowiak** [jmprathab/MyHome#196]
There is a need to create email templates.

Subtasks:
- Create an email template for a password reset
- Create an email template for creating an account

**Comment by mslowiak** [comment]
@jmprathab 
There is a need to create some email templates. 
Let me know your thoughts so we can proceed with creating subtasks

**Comment by DDmit04** [comment]
We can just use HTML thymeleaf template as email messages

**Comment by DDmit04** [comment]
Something like that already better than simple text


![image](https://user-images.githubusercontent.com/46588421/98776083-5d119c80-23ff-11eb-9fed-03c5fa35fb48.png)

**Comment by jmprathab** [comment]
@DDmit04 Yeah. This seems like a good thought.

**Comment by DDmit04** [comment]
I've been working on this. I created thymeleaf templates for emails and localization options for tem. Now I am rewriting the MailService tests and then creating a pull request.

**Comment by DDmit04** [comment]
I think we should create email confirmation sysem before send emails

**Comment by mslowiak** [comment]
@DDmit04 What do you mean?

**Comment by DDmit04** [comment]
@mslowiak When user registered we send email with activation code (or link) user use it and he's email become confirmed. Users witout confirmed email cant recive emails (for example user cant reset password). This way we can ensure that the email belongs to registered user

**Comment by DDmit04** [comment]
@mslowiak Also I suggest to only authenticate users with verified email addresses (make confirmation email part of registration)

**Comment by mslowiak** [comment]
@DDmit04 Yeah, the plan was to include this feature as well. This is why we got token_type property or something similiar in security tokens entity

**Comment by DDmit04** [comment]
@mslowiak Can I create Issues and work on email template and email confitmation?
