### ISSUE TITLE
PaymentController can only respond with 404 or with NullPointerException when creating Payment

### ISSUE THREAD

**Issue by rmgrimm** [jmprathab/MyHome#206]
## 🐛 Describe the bug

The PaymentController currently calls to the method `SchedulePaymentApiMapper#enrichedSchedulePaymentRequestToPaymentDto(...)` immediately before it calls the PaymentService to persist the payment:

```java
return houseMember.flatMap(member -> adminOptional.filter(
        admin -> isUserAdminOfCommunityHouse(member.getCommunityHouse(), admin)))
        .map(admin -> schedulePaymentApiMapper.enrichedSchedulePaymentRequestToPaymentDto(
            schedulePaymentApiMapper.enrichSchedulePaymentRequest(request, admin,
                houseMember.get())))
        .map(paymentService::schedulePayment)
```

From here, the PaymentController attempts to persist the payment into the database. Before persisting the payment, it first tries to persist an Admin User.

From PaymentSDJpaService.java:
```java
  @Override
  public PaymentDto schedulePayment(PaymentDto request) {
    generatePaymentId(request);
    return createPaymentInRepository(request);
  }

  private PaymentDto createPaymentInRepository(PaymentDto request) {
    Payment payment = paymentMapper.paymentDtoToPayment(request);

    adminRepository.save(payment.getAdmin());
    paymentRepository.save(payment);

    return paymentMapper.paymentToPaymentDto(payment);
  }
```

But the problem is that the method `enrichedSchedulePaymentRequestToPaymentDto` is annotated this way:

```java
@Mappings({
      @Mapping(target = "admin", ignore = true),
      @Mapping(target = "member", ignore = true)
  })
  PaymentDto enrichedSchedulePaymentRequestToPaymentDto(
      EnrichedSchedulePaymentRequest enrichedSchedulePaymentRequest);
```

Because admin is marked as ignore, the property in the resulting PaymentDto will be null. Then when `createPaymentInRepository` is called to convert to Payment, it takes a null Admin and brings it over as null. Then `adminRepository.save(payment.getAdmin());` is called and the request fails with a NullPointerException.

## ⚠️ Current behavior

All valid requests fail with NPE.

## ✅ Expected behavior

Valid requests should persist the payment into the database with correct attributes.

## 💣 Steps to reproduce

Remove the `@Disabled` annotation from the Integration Test that I put in #205 and then run the test.

**Comment by edwardUL99** [comment]
I can look at this as I did this code ages ago if nobody else wants to look at it? Haven't checked back in here in a while, so though I'd take a look again :)

**Comment by edwardUL99** [comment]
I could take a look at this as I did this code ages ago

**Comment by jmprathab** [comment]
@edwardUL99 Sure. Thanks for your time.

**Comment by edwardUL99** [comment]
@jmprathab @mslowiak @rmgrimm 
Descriptions aren't meant to be unique right? The description in Payment is defined as a unique column, but with the PaymentControllerIntegration test (I had to copy the code over into my branch as the pull request isn't merged yet), I didn't get a null pointer exception, instead of a unique key violation exception for description. When I remove the unique constraint, the test passes. I imagine descriptions shouldn't be unique right? So is it ok to leave it non-unique?

**Comment by mslowiak** [comment]
> @jmprathab @mslowiak @rmgrimm
> Descriptions aren't meant to be unique right? The description in Payment is defined as a unique column, but with the PaymentControllerIntegration test (I had to copy the code over into my branch as the pull request isn't merged yet), I didn't get a null pointer exception, instead of a unique key violation exception for description. When I remove the unique constraint, the test passes. I imagine descriptions shouldn't be unique right? So is it ok to leave it non-unique?

Yeah, they do not need to be unique
