### ISSUE TITLE
Implement DELETE house API

### ISSUE THREAD

**Issue by jmprathab** [jmprathab/MyHome#21]
## Implement DELETE house API

* Users should be able to delete a house which was added.
* REST endpoint should be `/communitites/{communityId}/houses/{houseId}`
* HTTP method should be `DELETE`

**Comment by gangadhargo** [comment]
sir, can I start contributing to this feature.

**Comment by jmprathab** [comment]
@gangadhargo Please feel free to send a PR. Please assign the issue to yourself so that people know you are working on this. Thanks for contributing.

**Comment by jmprathab** [comment]
@gangadhargo Please let me know if you need any help to understand the requirement.

**Comment by gangadhargo** [comment]
@jmprathab sure thanks

**Comment by Sountastic** [comment]
@jmprathab does it still need to be done? I would like to get involved ;)

**Comment by jmprathab** [comment]
@Sountastic Yes, it needs to be done. Thanks for your interest. Please assign it to yourself.

**Comment by Sountastic** [comment]
@jmprathab i couldn't assign myself because I'm not authorized for that. I created a pull request. Take a look if I should add something more ;)
