### ISSUE TITLE
forgot - reset password functionality

### ISSUE THREAD

**Issue by DDmit04** [jmprathab/MyHome#213]
## ⚠️ Is your feature request related to a problem? Please describe

Let users reset password with email

## 💡 Describe the solution you'd like

One problem here is to invalidate the current JWT token, with the current JWT implementation this is not possible. Now I think about JWT blacklist in redis or app DB

## 🤚 Do you want to develop this feature yourself?

- [x] Yes
- [ ] No

**Comment by mslowiak** [comment]
Closed via #215
