### ISSUE TITLE
Swagger docs are not generated from api.yaml specs

### ISSUE THREAD

**Issue by DDmit04** [jmprathab/MyHome#214]
## 🐛 Describe the bug

Information in Swagger.ui is different from `api.yaml`

## ⚠️ Current behavior

For all mappings responses Swagger diplay only 200 HTTP code

## ✅ Expected behavior

Full list of response codes defined in `api.yaml`

## 📷 Screenshots
in UI:

![image](https://user-images.githubusercontent.com/46588421/103703218-2fd50b00-4fb8-11eb-9a6b-ec8a0c3df7c2.png)

in `api.yaml`:

![image](https://user-images.githubusercontent.com/46588421/103703246-44b19e80-4fb8-11eb-9531-8c3768c46829.png)

**Comment by mslowiak** [comment]
That is not a bug. 
We not fully switched from the swagger and there is still  `org.springdoc:springdoc-openapi-ui:` used.

I will change that behavior soon :)

**Comment by mslowiak** [comment]
CC: @jmprathab 
Pull request is raised for that change #219
