### ISSUE TITLE
Error OpenApi on build

### ISSUE THREAD

**Issue by barddoo** [jmprathab/MyHome#217]
## 🐛 Describe the bug

Getting error when build the project

## ⚠️ Current behavior

Running `./gradlew assemble` and `./gradlew build` get into error
```
* What went wrong:
Execution failed for task ':api:generateOpenApiSpec'.
> There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
   | Error count: 1, Warning count: 0
  Errors: 
        -attribute .servers.invalid url : /v3
```

## 💣 Steps to reproduce

Clone repo, run `./gradlew assemble`

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/45905884/104107827-681d6780-529e-11eb-9da1-4916fc549d15.png)

## 📱 Tech info

- OS: Linux
- Library/App version: Java8

**Comment by DDmit04** [comment]
Strange I can't reproduce error on my PC (win10). I get success build.

This is my gradle info:

![image](https://user-images.githubusercontent.com/46588421/104130359-4648e100-5381-11eb-9277-5244cdcfbabe.png)

And I found strange thing with path: 

![image](https://user-images.githubusercontent.com/46588421/104130395-88722280-5381-11eb-971a-8f5dd4c2bfab.png)

I use `gradlew clean`, `gradlew build`, `gradlew assemble`

**Comment by barddoo** [comment]
Maybe it's related to Linux

**Comment by mslowiak** [comment]
@barddoo Do you resolved the issue or there is still a problem?

**Comment by barddoo** [comment]
Still get into error

**Comment by mslowiak** [comment]
@barddoo 
What is your gradle version?
Could you please change the openApiVersion version from `5.0.0-beta2` to `5.0.1` in `gradle.properties` and try again?

**Comment by mslowiak** [comment]
@barddoo 
I don't know why this problem occurs but we added the servers URL parameter in #241 so it should work from now :)
