### ISSUE TITLE
Move deleteBooking from AmenityController to BookingController

### ISSUE THREAD

**Issue by mslowiak** [jmprathab/MyHome#220]
It is more like a cleanup task.

Things to be done:
- move logic from `AmenityController` to `BookingController` (new class)
- rewrite API specs to `api.yaml` file
- change resource URL from `/bookings/{bookingId}` to `/amenities/{amenityId}/bookings/{bookingId}`

**Comment by hsergiu** [comment]
Can I take this one?

**Comment by mslowiak** [comment]
Sure, go ahead @hsergiu !

**Comment by prabinamatya** [comment]
@mslowiak  Is this still open? Can I take it?
