### ISSUE TITLE
Divide postman collection into directories

### ISSUE THREAD

**Issue by mslowiak** [jmprathab/MyHome#224]
Actually, postman collection has all requests in the root directory, would be nice to divide it per feature - community, documents, payments, etc.

Things that need to be done:
- Import postman collection to  your local environment (located under `/postman/MyHome.postman_collection.json`)
- Make directories (community, documents, payments,  etc)
- Move actual requests to proper directories
- Modify "Login user" request URL from `/users/login` to `/auth/login`
- Raise a PR :)

**Comment by ghost** [comment]
Hello, this is my first git project in a team and I am not sure if I understand the task correctly. You want to split the MyHome.postman_collection file into smaller files and put them in suitable folders. And then adjust the parser. Where can I find the parsers and where should the .json file be split?

**Comment by mslowiak** [comment]
Hi @JanneSickert! :) 

Currently, when you import the postman collection it looks like on the image below:
![image](https://user-images.githubusercontent.com/18486535/108736913-57654000-7532-11eb-83e5-8d83fb6a5509.png)

The idea is to group requests to different directories. We can create for example directory "authentication" and group there login and register requests, see below:
![image](https://user-images.githubusercontent.com/18486535/108737156-9abfae80-7532-11eb-9b85-0d1cdb68740c.png)


I encourage you to join our discord server: 
https://discord.gg/CngACKh
