### ISSUE TITLE
Move endpoints related to amenities from community tag

### ISSUE THREAD

**Issue by mslowiak** [jmprathab/MyHome#233]
Things to be done:
- Move GET `/communities/{communityId}/amenities` from `communities` tag to `amenities` tag in `api.yaml`
- Move POST `/communities/{communityId}/amenities` from `communities` tag to `amenities` tag in `api.yaml`
- Generate code from new specs
- Fix test classes

**Comment by ghost** [comment]
I will try to fix this issure.

**Comment by mslowiak** [comment]
@JanneSickert great, good luck!
