### ISSUE TITLE
Unit tests for new login endpoint logic

### ISSUE THREAD

**Issue by mslowiak** [jmprathab/MyHome#243]
We need to write tests for https://github.com/jmprathab/MyHome/pull/240/files.

Classes that should be covered:
- AuthenticationController.java
- AuthenticationSDJpaService.java 
- UserSDJpaService.java (method findUserByEmail)

**Comment by hsergiu** [comment]
I would like to write the tests. Would you let me do a PR after I am done with them?

**Comment by mslowiak** [comment]
Hi @hsergiu!
Feel free to start working on this issue.
All you need to do is to create a fork and raise PR when you will be done.
Take a look at our [contribution guide](https://github.com/jmprathab/MyHome/blob/master/CONTRIBUTING.md) before starting work :)
