### ISSUE TITLE
Implement DELETE admin API

### ISSUE THREAD

**Issue by jmprathab** [jmprathab/MyHome#32]
* Allow deletion of admin associated with a community.

**Comment by gangadhargo** [comment]
@jmprathab can you please assign this task to me. could you please share your email Id. I want to know more about the project and we can have a chat. my email Id: gangadhar.reddy7@gmail.com

**Comment by jmprathab** [comment]
@gangadhargo I have assigned the issue to you. My email id is jm.prathab@gmail.com
