### ISSUE TITLE
Convert codebase to use Java8

### ISSUE THREAD

**Issue by jmprathab** [jmprathab/MyHome#33]
### Following needs to be updated
1. `README.md`
2. `Dockerfile`
3. Codebase and gradle files.

**Comment by gangadhargo** [comment]
Hi, I have raised the pull request for this could you please review it. and I need one more help, could please let me know how to generate the bearer token as i am new to this. I tried but couldn't able to generate one. any suggestion please

**Comment by jmprathab** [comment]
@gangadhargo Thanks for the PR. 
You get the bearer token as part of Response headers when hitting `/users/login` API. Look out for `token` header.

**Comment by gangadhargo** [comment]
Able to generate the token thanks @jmprathab
