### ISSUE TITLE
Come up with test cases for all the APIs

### ISSUE THREAD

**Issue by jmprathab** [jmprathab/MyHome#38]
Unit tests for all API endpoints. Currently none of the APIs have test coverage :-(

**Comment by jmprathab** [comment]
FYI @amirabramovich

**Comment by mslowiak** [comment]
Hi there.
There is a `UserControllerTest` in test code but this is not an unit test. 
It is rather integration test.
What should be done with that?

**Comment by amirabramovich** [comment]
> Hi there.
> There is a `UserControllerTest` in test code but this is not an unit test.
> It is rather integration test.
> What should be done with that?

That is a unit test which test the controller, I agree that it reminds integration test a bit, but I don't have a better idea of testing the controllers. If you have any better idea, feel free to improve the tests.

**Comment by mslowiak** [comment]
@amirabramovich I will raise PR with proposal
