### ISSUE TITLE
Implement pagination for GET /users endpoint

### ISSUE THREAD

**Issue by jmprathab** [jmprathab/MyHome#41]
Implement pagination for GET /users endpoint

GET /users?limit=x -> List only x number of users
- 0 <= x <= 200 (Why 200? - Just a sensible limit)

GET /users?limit=x&start=y -> List next set of x users starting from y
- 0 <= y <= INTEGER_MAX

**Comment by mslowiak** [comment]
Should be closed because of https://github.com/jmprathab/MyHome/pull/53

**Comment by Tobi406** [comment]
#53 was reverted, but #65 was merged
