### ISSUE TITLE
Ability to add documents for a house member

### ISSUE THREAD

**Issue by jmprathab** [jmprathab/MyHome#47]
* Users should be able to upload an image(ID proof or any other government document for identification) for a house member.
* Limit the size and resolution of this image to a sensible value(Probably overall image size should be less than 250 KB).
* Ideally Frontend should compress the image, but then if frontend fails to do the compression to an acceptable limit then the server can compress and persist.

Notes for future: House member should not be able to delete the uploaded image. Only community admin should have the CRUD ability on these APIs or In general any of the CRUD APIs for a house member. But, then there is no permission enforcement anywhere as of now. So, permission enforcement will be taken up in future.

**Comment by mslowiak** [comment]
When this endpoint will be called/hitted? What is the use case?
