### ISSUE TITLE
All collection API should return sorted data

### ISSUE THREAD

**Issue by jmprathab** [jmprathab/MyHome#57]
## ⚠️ Is your feature request related to a problem? Please describe

Currently all API endpoints does not return sorted data. This becomes difficult when using pagination

## 💡 Describe the solution you'd like

All APIs which return collections should sort the result. Endpoint can get `sort` as a param and sort it based on that.

## 🤚 Do you want to develop this feature yourself?

- [ ] Yes
- [ ] No

**Comment by mslowiak** [comment]
I will work on that :+1:
