### ISSUE TITLE
Replace deprecated APIs

### ISSUE THREAD

**Issue by jmprathab** [jmprathab/MyHome#59]
## 🐛 Describe the bug

* Usage of deprecated APIs should be removed.

## ⚠️ Current behavior

* `MyHomeAuthenticationFilter` - This class uses deprecated `io.jsonwebtoken` APIs.

## ✅ Expected behavior

* Usage of deprecated APIs should be removed.

## 💣 Steps to reproduce

* Compiler the source code to get the exact warning.

## 📷 Screenshots

* None

## 📱 Tech info

- Device: All
- OS: All
- Library/App version: Java8

**Comment by edwardUL99** [comment]
I can take a look at this

**Comment by edwardUL99** [comment]
This is my first contribution to open-source so forgive my naivety. I got rid of the deprecated function calls and replaced them with the replacement functions. How do I test everything is supposed to work as expected?

**Comment by jmprathab** [comment]
@edwardUL99 Thanks for the interest! It is wonderful to hear that we are part of your first time contribution.
Once you remove the usage of deprecated API, you can hit `/users/login` endpoint and pass the necessary parameters to the REST call. We are expecting it to return a valid JWT as part of `token` header in HTTP response.

Tips
1. Import postman collection inside postman folder, this has lot of endpoints pre-configured for testing
2. Once application is started open `http://localhost:8080/docs/swagger-ui.html` which lists all the available endpoints.

Feel free to reach out to us either here or on [Discord](https://discord.gg/CngACKh) if you need any more help.

**Comment by jmprathab** [comment]
Fixed with PR https://github.com/jmprathab/MyHome/pull/74. Hence closing.
