### ISSUE TITLE
Enforce expiration validation in JWT

### ISSUE THREAD

**Issue by jmprathab** [jmprathab/MyHome#77]
Enforce expiration validation in JWT

## ⚠️ Current behavior

* JWT expiration date is not taken into account during validation.

## ✅ Expected behavior

* A JWT should not be valid once it has expired.

## 💣 Steps to reproduce

* Write a Unit test and pass an invalid JWT.

**Comment by mslowiak** [comment]
I can take this. 
@jmprathab Do you even considered to switch jwt library to `com.auth0:java-jwt`?
It is simpler to use IMHO.
![image](https://user-images.githubusercontent.com/18486535/88808248-ea174980-d1b2-11ea-90dd-c1189fc005e4.png)

**Comment by Govardhan10** [comment]
I tried to reproduce this issue by changing the expiry time to 60 seconds for local debugging , after 60 seconds I am getting 403 (looks like working fine in my local environment)

Please find the trace :
JWT expired at 2020-07-29T14:51:22Z. Current time: 2020-07-29T14:52:14Z, a difference of 52632 milliseconds.

**Comment by jmprathab** [comment]
> I tried to reproduce this issue by changing the expiry time to 60 seconds for local debugging , after 60 seconds I am getting 403 (looks like working fine in my local environment)
> 
> Please find the trace :
> JWT expired at 2020-07-29T14:51:22Z. Current time: 2020-07-29T14:52:14Z, a difference of 52632 milliseconds.

Many thanks for checking 🙏. I was never able to see a visible code which does the expiration time validation, so I raised an tracking issue. Let me close this. Thanks again 🙌

**Comment by jmprathab** [comment]
> I can take this.
> @jmprathab Do you even considered to switch jwt library to `com.auth0:java-jwt`?
> It is simpler to use IMHO.
> ![image](https://user-images.githubusercontent.com/18486535/88808248-ea174980-d1b2-11ea-90dd-c1189fc005e4.png)

Now I remember using `com.auth0:java-jwt` for one of my old project. Does it offer anything more in functionality other than ease of use?

Your call. If you feel it is better to migrate to `com.auth0:java-jwt` we can do so.

But, I would request you to raise a PR after approving jmprathab/MyHome#76 😊
