### ISSUE TITLE
Make all sensitive content in properties file encrypted

### ISSUE THREAD

**Issue by jmprathab** [jmprathab/MyHome#8]
## Make all sensitive content in properties file encrypted

* Currently sensitive content like `JWT Secret Key` is stored un-encrypted in `application.yml` file.
* These sensitive content must be encrypted and stored in `application.yml` file.

**Comment by weakphish** [comment]
Hey, I'd like to work on this - what kind of encryption did you have in mind? And what kind of process if any did you have in mind? Thanks.

**Comment by jmprathab** [comment]
@John123Allison Thanks for your time and interest.

This issue was created when the project had a micro-service architecture. I originally wanted to use Spring cloud config server's encryption/decryption [functionality](https://cloud.spring.io/spring-cloud-static/spring-cloud-config/1.3.0.RELEASE/#_encryption_and_decryption). I wanted to encrypt `token.secret` which is present in [application.yml](src/main/resources/application.yml) file. However, now the project is a monolith and does not have a config server anymore.

What approach do you suggest to encrypt the secret value? Now I personally think it should be left un-encrypted.

I would like to know your thoughts. Based, on the comment I can close this issue.

Thanks again.

**Comment by weakphish** [comment]
Hey,

I agree with your assessment, go ahead and close :)
Thanks for the reply!
