### ISSUE TITLE
Test database data loading control

### ISSUE THREAD

**Issue by DDmit04** [jmprathab/MyHome#80]
## 🐛 Describe the bug

Loading test data to databse can't be configured externaly (load data or not)

## ⚠️ Current behavior

Loading test data in database controls from `DataLoader` code
```
@Override public void run(String... args) throws Exception {
    loadData();
  }
```
## ✅ Expected behavior

application.yml variable that controls the loaded data or not. May be create separate application.yml files for dev, prod and tests.

**Comment by amirabramovich** [comment]
Can you please explain the purpose of this class (or actually whole package)? 
It seems like test code, it should be in test package and not src...

**Comment by jmprathab** [comment]
> Can you please explain the purpose of this class (or actually whole package)?
> It seems like test code, it should be in test package and not src...

@amirabramovich The purpose of this class is to provide some default values during startup. The idea is to give anyone who tries out the application for the first time with good values. Also, it becomes easier to quickly test developed features.

So, yeah, these are not test classes.

**Comment by amirabramovich** [comment]
Hi, I found this solution which seems pretty good:
https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto-database-initialization

I can make this import.sql file in order to solve the bug. You can assign this issue to me.

**Comment by jmprathab** [comment]
@amirabramovich I would suggest to use `data.sql`.

**Comment by jmprathab** [comment]
@amirabramovich I think as of now the current approach(`DataLoader.java`) works fine. I know it is difficult to write SQL queries to load a lot of data and that too to multiple tables.

Please feel free to take this up with less priority if you feel so.

**Comment by mslowiak** [comment]
@jmprathab We can also switch approach to liquibase connected with a dedicated profile. It supports Java dataloader classes migration.
https://stackoverflow.com/questions/11987460/java-code-changeset-in-liquibase

**Comment by jmprathab** [comment]
This is the first time I am hearing about liquibase. I am just curious about what value addition does it bring? I need to explore on this.

**Comment by mslowiak** [comment]
It is a tool that help with database version control. Check this out.

**Comment by jmprathab** [comment]
Closing this issue for now with PR#85. Let us open new issue for enhancement.
