### ISSUE TITLE
Compress images on the fly which are uploaded

### ISSUE THREAD

**Issue by jmprathab** [jmprathab/MyHome#82]
## Compress the images uploaded to the document endpoint without staging

* As of now, the document/image which is uploaded is staged and then compressed and stored to DB.

## 💡 Describe the solution you'd like

* This should be done on the fly without staging.

**Comment by jmprathab** [comment]
CC: @mslowiak and @DDmit04

**Comment by DDmit04** [comment]
It is suitable? [Commit](https://github.com/jmprathab/MyHome/pull/75/commits/14ade69f34d99ce4f8d26b651133621d9576be28)

**Comment by jmprathab** [comment]
This stages the file right?

**Comment by DDmit04** [comment]
In this Commit already not. I replace File by ByteStream

**Comment by jmprathab** [comment]
@DDmit04 So are you saying with your changes, We are not writing the image to a file and then storing to a DB ?
Instead, we are directly storing the image to a database?

It looks like we are writing to a [file](https://github.com/jmprathab/MyHome/pull/75/commits/14ade69f34d99ce4f8d26b651133621d9576be28#diff-80b50e57606c7485c463e68e6bca357cR113)

**Comment by DDmit04** [comment]
This method write image to byteStream. In previos version I wrote image to FileSteam which created from file. Now I directly create byteStream and write without file.

**Comment by DDmit04** [comment]
No files creating in process. I Just forgot rename method, sorry.

**Comment by jmprathab** [comment]
Absolutely not a problem! thanks for clarifying. Please close this issue once you rename the methods. Thanks!

**Comment by DDmit04** [comment]
Ok

**Comment by DDmit04** [comment]
It seems that necessary changes already merged in master [here](https://github.com/jmprathab/MyHome/blob/master/src/main/java/com/myhome/services/springdatajpa/HouseMemberDocumentSDJpaService.java#L118)

**Comment by jmprathab** [comment]
Seems like it is [not completely](https://github.com/jmprathab/MyHome/blob/master/src/main/java/com/myhome/services/springdatajpa/HouseMemberDocumentSDJpaService.java#L113) renamed.

**Comment by jmprathab** [comment]
Fixed by PR https://github.com/jmprathab/MyHome/pull/86. Hence closing this issue.
