### ISSUE TITLE
Tests takes a lot of time to execute

### ISSUE THREAD

**Issue by jmprathab** [jmprathab/MyHome#83]
## 🐛 Describe the bug

* It takes a lot of time to execute tests

## ⚠️ Current behavior

* Tests takes close to 10 mins to execute.

## ✅ Expected behavior

* It should take considerably less time to execute

## 💣 Steps to reproduce

* `gradlew build`

**Comment by Govardhan10** [comment]
Hi Prathab,

I have taken the test result report of all tests , according the results it is taking around 2 secs to complete execution of the tests
![TestResults](https://user-images.githubusercontent.com/37766383/89096492-b297df80-d3f4-11ea-8e9e-9d7dbf05b97e.png)

**Comment by jmprathab** [comment]
Hi @Govardhan10,

How were these tests executed? Using what command. I just ran `gradle build` It took almost 8 minutes to complete.

![Screenshot 2020-08-01 at 3 06 40 PM](https://user-images.githubusercontent.com/11979066/89098843-a9187280-d408-11ea-8c5d-fb5b0b7d6922.png)

**Comment by jmprathab** [comment]
Closing this as Not reproducible.
