### ISSUE TITLE
Create part of tests for HouseMemberDocument service (create and update document methods) 

### ISSUE THREAD

**Issue by DDmit04** [jmprathab/MyHome#84]
## ⚠️ Is your feature request related to a problem? Please describe

Create rest of unit tests for HouseMemberDocument service 

## 💡 Describe the solution you'd like

Create separate test file with applicationContext load

## 🤚 Do you want to develop this feature yourself?

- [x] Yes
- [ ] No

**Comment by jmprathab** [comment]
@DDmit04 My suggestion is to take a quick look at the implementation of `HealthCheckControllerIntegrationTest.java`. This test does not take a lot of time to execute.

**Comment by DDmit04** [comment]
thx
