### ISSUE TITLE
House member documents integration tests

### ISSUE THREAD

**Issue by DDmit04** [jmprathab/MyHome#87]
## ⚠️ Is your feature request related to a problem? Please describe

add integration tests for `HouseMemberDocumentController` and `HouseMemberDocumentService`

## 🤚 Do you want to develop this feature yourself?

- [x] Yes
- [ ] No

**Comment by DDmit04** [comment]
Is this issue closed? I made mistake and write `Closing` instead `Closes` in my pull request description

**Comment by jmprathab** [comment]
@DDmit04 Please close this in case you have done all the changes for this.
