### ISSUE TITLE
CommunityAdminRepository not storing unique admins

### ISSUE THREAD

**Issue by edwardUL99** [jmprathab/MyHome#91]
## 🐛 Describe the bug

Added a method to CommunityAdminRepisitory to findAdminById but when used, an exception is thrown saying multiple results are returned where only one is expected. This is because it appears that multiple community admins with the same ID are being added to the repository

## ⚠️ Current behavior

When adding a community admin to a community, the community controller takes the admin list and adds it to the community's admin list. It then saves the community admin to CommunityAdminRepository. However when the community is being saved also, this set of admins is being saved, which appears to be why admins are getting duplicated in the repository

## ✅ Expected behavior

When findByAdminId is called it should return 1 community admin or nothing if not found.

Each row in the community repository should be unique and not duplicated

## 💣 Steps to reproduce

- Add a findByAdminId to the CommunityAdminRepository which takes the parameter String adminId
- Somewhere in a controller method that takes an admin id, call the findByAdminId method (you don't need to do anything with the result)
- Build using gradlew assemble. 
- Run the application using the jar file
- List users and choose one of the user and copy it's user id
- List communities and choose one community id to copy
- Add the user id you copied to the community admins by using the Add admin to Community request
- With the endpoint that you added the findByAdminId call to, run it and the exception should occur

## 📱 Tech info

- Device: Docker/Jar file
- OS: Ubuntu 20.04
- Library/App version: Java 8

**Comment by DDmit04** [comment]
add that POST (`/communities/{communityId}/admins`) returns empty community in case of communityId is invalid, this is correct behavior?

**Comment by DDmit04** [comment]
can I work on this?

**Comment by DDmit04** [comment]
There is no admin comtroll endpoint. Where new admins must be created? Now they creating in `CommunityService` when list of admins adding to community. I think we should create CRUD for controll `CommunityAdmin` and `CommunityHouse` (`HouseController` can't create or delete houses)

**Comment by edwardUL99** [comment]
@DDmit04 I noticed that and because of it I am having trouble creating unit tests for the Payments request because I need a house to be created and add a house member added to it to test some features of the payments. Maybe @jmprathab has suggestions

**Comment by jmprathab** [comment]
> add that POST (`/communities/{communityId}/admins`) returns empty community in case of communityId is invalid, this is correct behavior?

This is not correct. It should ideally return HTTP 400 on invalid community id.

**Comment by jmprathab** [comment]
> There is no admin comtroll endpoint. Where new admins must be created? Now they creating in `CommunityService` when list of admins adding to community. I think we should create CRUD for controll `CommunityAdmin` and `CommunityHouse` (`HouseController` can't create or delete houses)

@DDmit04  and @edwardUL99 

**Short answer:** It was a conscious decision to not allow `HouseController` to create and delete houses.

**Long answer:**
Creating and deleting house always needs context of community(`communityId`). If this is implemented in `HouseController` then users of our REST API will need to send communityId as part of request body and server will need to validate it for every request.

But, if this API is rather in `CommunityController`, consumer of REST API will need to pass the communityId as part of URI to make the API call. So, following the best practice of REST API design, it is in `CommunityController`.

Also, it becomes easier to implement `User access control` in future. For instance, Only `CommunityAdmin` will have access to `/communities/**` endpoint and thereby only they can Add and Delete houses from a community.

Having said these points. It is absolutely fine to move it to `HouseController` if you guys feel so. My suggestion is to leave it as such.

CC: @mslowiak

**Comment by DDmit04** [comment]
Where in app admins should be created?
